version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4173:4173"
    volumes:
      - ./app/InventoryManagement/client/.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./app/InventoryManagement/server/.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: always
