services:
  client:
    image: dhishon/inventory-client:latest
    ports:
      - "4173:4173"
    volumes:
      - /home/dhishon/app/InventoryManagement/client/.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: always

  server:
    image: dhishon/inventory-server:latest
    ports:
      - "4000:4000"
    volumes:
      - /home/dhishon/app/InventoryManagement/server/.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: always
