services:
  client:
    image: dhishon/inventory-client:latest
    ports:
      - "4173:4173"
    env_file:
      - /home/dhishon/app/InventoryManagement/client/.env
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    restart: always
    volumes:
      - /home/dhishon/app/InventoryManagement/client/.env:/usr/src/app/.env:ro

  server:
    image: dhishon/inventory-server:latest
    ports:
      - "4000:4000"
    env_file:
      - /home/dhishon/app/InventoryManagement/server/.env
    restart: always
    volumes:
      - /home/dhishon/app/InventoryManagement/server/.env:/usr/src/app/.env:ro
