version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4173:4173"
    volumes:
      - ./client/.env:/usr/src/app/.env:ro  # Corrected path
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server/.env:/usr/src/app/.env:ro  # Corrected path
    environment:
      - NODE_ENV=production
    restart: always
